Caffeina/Models/Categorie.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;

namespace Caffeina.Models
{
    public partial class Categorie
    {
        public Categorie()
        {
            Produits = new HashSet<Produit>();
        }

        [Key]
        public int IdCategorie { get; set; }
        public string Designation { get; set; } = null!;
        public string SourceImage { get; set; } = null!;
        public DateTime? DateAjout { get; set; }

        public virtual ICollection<Produit> Produits { get; set; }
    }
}

Caffeina/Controllers/CategorieController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using Caffeina.Models;

namespace Caffeina.Controllers
{
    public class CategorieController : Controller
    {
        private readonly caffeinaContext _context;
        private static int IDCATEGORIE = 0;
        public CategorieController(caffeinaContext context)
        {
            IDCATEGORIE++;
            _context = context;
        }

        // GET: Categorie
        [Route("/admin/list-categorie")]
        public async Task<IActionResult> Index()
        {
              return _context.Categories != null ? 
                          View(await _context.Categories.ToListAsync()) :
                          Problem("Entity set 'caffeinaContext.Categories'  is null.");
        }

        // GET: Categorie/Details/5
        [Route("/admin/detail-categorie/{id}")]
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null || _context.Categories == null)
            {
                return NotFound();
            }

            var categorie = await _context.Categories
                .FirstOrDefaultAsync(m => m.IdCategorie == id);
            if (categorie == null)
            {
                return NotFound();
            }

            return View(categorie);
        }

        // GET: Categorie/Create
        [Route("/admin/ajouter-categorie")]
        public IActionResult Create()
        {
            return View();
        }

        // POST: Categorie/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [Route("/admin/ajouter-categorie")]
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("IdCategorie,Designation,SourceImage,DateAjout")] Categorie categorie)
        {
            categorie.DateAjout = DateTime.Now;
            categorie.IdCategorie = IDCATEGORIE;
            if (ModelState.IsValid)
            {
                _context.Add(categorie);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            return View(categorie);
        }

        // GET: Categorie/Edit/5
        [Route("/admin/modifier-categorie/{id}")]
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null || _context.Categories == null)
            {
                return NotFound();
            }

            var categorie = await _context.Categories.FindAsync(id);
            if (categorie == null)
            {
                return NotFound();
            }
            return View(categorie);
        }

        // POST: Categorie/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [Route("/admin/modifier-categorie/{id}")]
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("IdCategorie,Designation,SourceImage,DateAjout")] Categorie categorie)
        {
            if (id != categorie.IdCategorie)
            {
                return NotFound();
            }
            categorie.DateAjout = DateTime.Now;
            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(categorie);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!CategorieExists(categorie.IdCategorie))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(categorie);
        }

        // GET: Categorie/Delete/5
        [Route("/admin/supprimmer-categorie/{id}")]
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null || _context.Categories == null)
            {
                return NotFound();
            }

            var categorie = await _context.Categories
                .FirstOrDefaultAsync(m => m.IdCategorie == id);
            if (categorie == null)
            {
                return NotFound();
            }

            return View(categorie);
        }

        // POST: Categorie/Delete/5
        [Route("/admin/supprimmer-categorie/{id}")]
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            if (_context.Categories == null)
            {
                return Problem("Entity set 'caffeinaContext.Categories'  is null.");
            }
            var categorie = await _context.Categories.FindAsync(id);
            if (categorie != null)
            {
                _context.Categories.Remove(categorie);
            }
            
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool CategorieExists(int id)
        {
          return (_context.Categories?.Any(e => e.IdCategorie == id)).GetValueOrDefault();
        }
    }
}

Caffeina/Views/Categorie/Create.cshtml
@model Caffeina.Models.Categorie

@{
    ViewData["Title"] = "Ajouter catégorie";
    Layout = "_layoutadmine";
}

<div id="wrapper">

    <!-- Sidebar -->
    @Html.Partial("_Navbar")
    <!-- End of Sidebar -->
    <!-- Content Wrapper -->
    <div id="content-wrapper" class="d-flex flex-column">
        <!-- Main Content -->
        <div id="content">
            <!-- Topbar -->
            @Html.Partial("_Topbar")
            <!-- End of Topbar -->
            <!-- Begin Page Content -->
            <div class="container-fluid">

                <div class="d-sm-flex align-items-center justify-content-between mb-4">
                    <h1 class="h3 mb-0 text-gray-800">Ajouter - Catégorie</h1>
                </div>
                <form asp-action="Create">
                    <div asp-validation-summary="ModelOnly" class="text-danger"></div>
                    <div class="col">
                        <div data-mdb-input-init class="form-outline mb-4">
                            <label asp-for="Designation" class="control-label"></label>
                            <input asp-for="Designation" class="form-control" />
                            <span asp-validation-for="Designation" class="text-danger"></span>
                        </div>
                    </div>
                    <div class="col">
                        <div data-mdb-input-init class="form-outline mb-4">
                            <label asp-for="SourceImage" class="control-label"></label>
                            <input type="file" asp-for="SourceImage" class="form-control-file" />
                            <span asp-validation-for="SourceImage" class="text-danger"></span>
                        </div>
                    </div>
                    <div class="form-group">
                        <input type="submit" value="Ajouter" data-mdb-input-init class="btn btn-admin btn-block mb-4" />
                    </div>
                </form>
                <div>
                    <a asp-action="Index" class="a-lien">Voir list</a>
                </div>
            </div>
            <!-- /.container-fluid -->
        </div>
        <!-- End of Main Content -->
        <!-- Footer -->
        @Html.Partial("_Footer")
        <!-- End of Footer -->
    </div>
    <!-- End of Content Wrapper -->
</div>



@section Scripts {
    @{
        await Html.RenderPartialAsync("_ValidationScriptsPartial");
    }
}

Caffeina/Views/Categorie/Delete.cshtml
@model Caffeina.Models.Categorie

@{
    ViewData["Title"] = "Supprimer catégorie";
    Layout = "_layoutadmine";
}

<div id="wrapper">

    <!-- Sidebar -->
    @Html.Partial("_Navbar")
    <!-- End of Sidebar -->
    <!-- Content Wrapper -->
    <div id="content-wrapper" class="d-flex flex-column">
        <!-- Main Content -->
        <div id="content">
            <!-- Topbar -->
            @Html.Partial("_Topbar")
            <!-- End of Topbar -->
            <!-- Begin Page Content -->
            <div class="container-fluid">

                <div class="d-sm-flex align-items-center justify-content-between mb-4">
                    <h1 class="h3 mb-0 text-gray-800">Supprimer - Catégorie</h1>
                    <h3>Êtes-vous sûr de vouloir supprimer ceci ?</h3>
                </div>
                <div>
                    <h4>Categorie</h4>
                    <hr />
                    <dl class="row">
                        <dt class="col-sm-2">
                            @Html.DisplayNameFor(model => model.Designation)
                        </dt>
                        <dd class="col-sm-10">
                            @Html.DisplayFor(model => model.Designation)
                        </dd>
                        <dt class="col-sm-2">
                            @Html.DisplayNameFor(model => model.SourceImage)
                        </dt>
                        <dd class="col-sm-10">
                            @Html.DisplayFor(model => model.SourceImage)
                        </dd>
                        <dt class="col-sm-2">
                            @Html.DisplayNameFor(model => model.DateAjout)
                        </dt>
                        <dd class="col-sm-10">
                            @Html.DisplayFor(model => model.DateAjout)
                        </dd>
                    </dl>

                    <form asp-action="Delete">
                        <input type="hidden" asp-for="IdCategorie" />
                        <input type="submit" value="Delete" class="btn btn-danger" /> |
                        <a asp-action="Index">Voir listet</a>
                    </form>
                </div>
                
            </div>
            <!-- /.container-fluid -->
        </div>
        <!-- End of Main Content -->
        <!-- Footer -->
        @Html.Partial("_Footer")
        <!-- End of Footer -->
    </div>
    <!-- End of Content Wrapper -->
</div>

@section Scripts {
    @{
        await Html.RenderPartialAsync("_ValidationScriptsPartial");
    }
}

Caffeina/Views/Categorie/Details.cshtml
@model Caffeina.Models.Categorie

@{
    ViewData["Title"] = "Ajouter catégorie";
    Layout = "_layoutadmine";
}

<div id="wrapper">

    <!-- Sidebar -->
    @Html.Partial("_Navbar")
    <!-- End of Sidebar -->
    <!-- Content Wrapper -->
    <div id="content-wrapper" class="d-flex flex-column">
        <!-- Main Content -->
        <div id="content">
            <!-- Topbar -->
            @Html.Partial("_Topbar")
            <!-- End of Topbar -->
            <!-- Begin Page Content -->
            <div class="container-fluid">
                <div class="d-sm-flex align-items-center justify-content-between mb-4">
                    <h1 class="h3 mb-0 text-gray-800">Détail - Catégorie</h1>
                </div>
                <dl class="row">
                    <dt class="col-sm-2">
                        @Html.DisplayNameFor(model => model.Designation)
                    </dt>
                    <dd class="col-sm-10">
                        @Html.DisplayFor(model => model.Designation)
                    </dd>
                    <dt class="col-sm-2">
                        @Html.DisplayNameFor(model => model.SourceImage)
                    </dt>
                    <dd class="col-sm-10">
                        @Html.DisplayFor(model => model.SourceImage)
                    </dd>
                    <dt class="col-sm-2">
                        @Html.DisplayNameFor(model => model.DateAjout)
                    </dt>
                    <dd class="col-sm-10">
                        @Html.DisplayFor(model => model.DateAjout)
                    </dd>
                </dl>
                <div>
                    <a asp-action="Edit" asp-route-id="@Model?.IdCategorie" class="a-lien">Modifier</a> |
                    <a asp-action="Index" class="a-lien">Voir liste</a>
                </div>
            </div>
            <!-- /.container-fluid -->
        </div>
        <!-- End of Main Content -->
        <!-- Footer -->
        @Html.Partial("_Footer")
        <!-- End of Footer -->
    </div>
    <!-- End of Content Wrapper -->
</div>



@section Scripts {
    @{
        await Html.RenderPartialAsync("_ValidationScriptsPartial");
    }
}

Caffeina/Views/Categorie/Edit.cshtml
@model Caffeina.Models.Categorie

@{
    ViewData["Title"] = "Modifier catégorie";
    Layout = "_layoutadmine";
}
<div id="wrapper">

    <!-- Sidebar -->
    @Html.Partial("_Navbar")
    <!-- End of Sidebar -->
    <!-- Content Wrapper -->
    <div id="content-wrapper" class="d-flex flex-column">
        <!-- Main Content -->
        <div id="content">
            <!-- Topbar -->
            @Html.Partial("_Topbar")
            <!-- End of Topbar -->
            <!-- Begin Page Content -->
            <div class="container-fluid">
                <div class="d-sm-flex align-items-center justify-content-between mb-4">
                    <h1 class="h3 mb-0 text-gray-800">Ajouter - Catégorie</h1>
                </div>
                <form asp-controller="Categorie" asp-action="Edit" method="post">
                    <div asp-validation-summary="ModelOnly" class="text-danger"></div>
                    <input type="hidden" asp-for="IdCategorie" />
                    <div class="col">
                        <div data-mdb-input-init class="form-outline mb-4">
                            <label asp-for="Designation" class="control-label"></label>
                            <input asp-for="Designation" class="form-control" />
                            <span asp-validation-for="Designation" class="text-danger"></span>
                        </div>
                    </div>
                    <div class="col">
                        <div data-mdb-input-init class="form-outline mb-4">
                            <label asp-for="SourceImage" class="control-label"></label>
                            <input type="file" asp-for="SourceImage" class="form-control-file" />
                            <span asp-validation-for="SourceImage" class="text-danger"></span>
                        </div>
                    </div>
                    <div class="form-group">
                        <input type="submit" value="Modifier" data-mdb-input-init class="btn btn-admin btn-block mb-4" />
                    </div>
                </form>
                <div>
                    <a asp-action="Index">Voir liste</a>
                </div>
            </div>
            <!-- /.container-fluid -->
        </div>
        <!-- End of Main Content -->
        <!-- Footer -->
        @Html.Partial("_Footer")
        <!-- End of Footer -->
    </div>
    <!-- End of Content Wrapper -->
</div>



@section Scripts {
    @{
        await Html.RenderPartialAsync("_ValidationScriptsPartial");
    }
}

Caffeina/Views/Categorie/Index.cshtml
@model IEnumerable<Caffeina.Models.Categorie>

@{
    ViewData["Title"] = "Liste des categories";
    Layout = "_layoutadmine";
}


<div id="wrapper">

    @*Sidebar*@
    @Html.Partial("_Navbar")
    @*End of Sidebar*@
    @*Content Wrapper*@
    <div id="content-wrapper" class="d-flex flex-column">

        @*Main Content*@
        <div id="content">

            @*Topbar*@
            @Html.Partial("_Topbar")
            @*End of Topbar*@
            @*Begin Page Content*@
            <div class="container-fluid">

                @*Page Heading*@
                <h1 class="h3 mb-2 text-gray-800">Listes</h1>
                <p class="mb-4">
                    <a asp-action="Create" class="a-lien">Ajouter nouveau catégories</a>
                </p>

                @*DataTales Example*@
                <div class="card shadow mb-4">
                    <div class="card-header py-3">
                        <h6 class="m-0 font-weight-bold text-primary">Catégories</h6>
                    </div>
                    <div class="card-body">
                        <div class="table-responsive">
                            <table class="table table-bordered" id="dataTable" width="100%" cellspacing="0">
                                <thead>
                                    <tr>
                                        <th>
                                            @Html.DisplayNameFor(model => model.Designation)
                                        </th>
                                        <th>
                                            @Html.DisplayNameFor(model => model.SourceImage)
                                        </th>
                                        <th>
                                            @Html.DisplayNameFor(model => model.DateAjout)
                                        </th>
                                        <th>Actions</th>
                                    </tr>
                                </thead>
                                <tbody>
                                    @foreach (var item in Model)
                                    {
                                        <tr>
                                            <td>
                                                @Html.DisplayFor(modelItem => item.Designation)
                                            </td>
                                            <td>
                                                @Html.DisplayFor(modelItem => item.SourceImage)
                                            </td>
                                            <td>
                                                @Html.DisplayFor(modelItem => item.DateAjout)
                                            </td>
                                            <td>
                                                <a asp-action="Edit" asp-route-id="@item.IdCategorie"><svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-pencil-square" viewBox="0 0 16 16">
                                                    <path d="M15.502 1.94a.5.5 0 0 1 0 .706L14.459 3.69l-2-2L13.502.646a.5.5 0 0 1 .707 0l1.293 1.293zm-1.75 2.456-2-2L4.939 9.21a.5.5 0 0 0-.121.196l-.805 2.414a.25.25 0 0 0 .316.316l2.414-.805a.5.5 0 0 0 .196-.12l6.813-6.814z" />
                                                    <path fill-rule="evenodd" d="M1 13.5A1.5 1.5 0 0 0 2.5 15h11a1.5 1.5 0 0 0 1.5-1.5v-6a.5.5 0 0 0-1 0v6a.5.5 0 0 1-.5.5h-11a.5.5 0 0 1-.5-.5v-11a.5.5 0 0 1 .5-.5H9a.5.5 0 0 0 0-1H2.5A1.5 1.5 0 0 0 1 2.5z" />
                                                    </svg></a> |
                                                <a asp-action="Details" asp-route-id="@item.IdCategorie"><svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-info-circle" viewBox="0 0 16 16">
                                                    <path d="M8 15A7 7 0 1 1 8 1a7 7 0 0 1 0 14m0 1A8 8 0 1 0 8 0a8 8 0 0 0 0 16" />
                                                    <path d="m8.93 6.588-2.29.287-.082.38.45.083c.294.07.352.176.288.469l-.738 3.468c-.194.897.105 1.319.808 1.319.545 0 1.178-.252 1.465-.598l.088-.416c-.2.176-.492.246-.686.246-.275 0-.375-.193-.304-.533zM9 4.5a1 1 0 1 1-2 0 1 1 0 0 1 2 0" />
                                                      </svg></a> |
                                                <a asp-action="Delete" asp-route-id="@item.IdCategorie"><svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-trash3" viewBox="0 0 16 16">
                                                    <path d="M6.5 1h3a.5.5 0 0 1 .5.5v1H6v-1a.5.5 0 0 1 .5-.5M11 2.5v-1A1.5 1.5 0 0 0 9.5 0h-3A1.5 1.5 0 0 0 5 1.5v1H1.5a.5.5 0 0 0 0 1h.538l.853 10.66A2 2 0 0 0 4.885 16h6.23a2 2 0 0 0 1.994-1.84l.853-10.66h.538a.5.5 0 0 0 0-1zm1.958 1-.846 10.58a1 1 0 0 1-.997.92h-6.23a1 1 0 0 1-.997-.92L3.042 3.5zm-7.487 1a.5.5 0 0 1 .528.47l.5 8.5a.5.5 0 0 1-.998.06L5 5.03a.5.5 0 0 1 .47-.53Zm5.058 0a.5.5 0 0 1 .47.53l-.5 8.5a.5.5 0 1 1-.998-.06l.5-8.5a.5.5 0 0 1 .528-.47M8 4.5a.5.5 0 0 1 .5.5v8.5a.5.5 0 0 1-1 0V5a.5.5 0 0 1 .5-.5" />
                                                      </svg></a>
                                            </td>
                                        </tr>
                                    }
                                </tbody>
                            </table>
                        </div>
                    </div>
                </div>

            </div>
            <!--/.container-fluid-->

        </div>
        <!--End of Main Content-->
        <!--Footer-->
        @Html.Partial("_Footer")
        <!--End of Footer-->

    </div>
    <!--End of Content Wrapper-->

</div>